# Generated by Django 3.1.3 on 2022-06-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_question_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
