# Generated by Django 3.1.3 on 2022-06-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_auto_20220622_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
    ]
