# Generated by Django 3.1.3 on 2022-06-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0014_auto_20220622_0235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
