# Generated by Django 3.1.3 on 2022-06-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0016_auto_20220622_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
    ]
