# Generated by Django 3.1.3 on 2022-06-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0025_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
